<?php
declare (strict_types = 1);

namespace app\index\controller;

use app\BaseController;
use app\common\exception\BadRequest as BadRequestException;
use app\common\model\User as UserModel;
use app\common\service\Jwt as JwtService;
use think\App;

class Base extends BaseController
{
    /*
     * 开启批量验证
     */
    protected $batchValidate = true;

    /*
     * 用户主键
     */
    protected $userId = 0;

    /*
     * 构造函数
     */
    public function __construct(App $app)
    {
        parent::__construct($app);
    }

    /*
     * 初始化函数
     */
    protected function initialize()
    {
        $jwt = JwtService::getInstance();
        if($jwt->getTableName() === 'user'){
            //验证token中的id有效性，可增加即时性
            $id = $jwt->getTableId();
            $user = UserModel::findOrEmpty($id);
            if($user->isEmpty()) throw new BadRequestException(['errorMessage' => '用户不存在或已删除']);
            if($user->is_use == 2) throw new BadRequestException(['errorMessage' => '账号未启用']);
            $this->userId = $user->id;
        }

        parent::initialize(); // TODO: Change the autogenerated stub
    }
}
