<?php
declare (strict_types = 1);

namespace app\index\controller;

use app\BaseController;
use app\common\exception\BadRequest as BadRequestException;
use app\common\model\User as UserModel;
use app\common\service\Jwt as JwtService;
use app\common\service\Redis as RedisService;
use think\App;

class Base extends BaseController
{
    /*
     * 开启批量验证
     */
    protected $batchValidate = true;

    /*
     * 用户主键
     */
    protected $userId = 0;

    /*
     * 构造函数
     */
    public function __construct(App $app)
    {
        parent::__construct($app);
    }

    /*
     * 初始化函数
     */
    protected function initialize()
    {
        $jwt = JwtService::getInstance();
        if($jwt->getTableName() === 'user'){
            $redis = RedisService::getInstance();
            $userId = $redis->get('USER:ID:' . $jwt->getTableId());
            if(!$userId) throw new BadRequestException(['errorMessage' => '用户ID缓存不存在或已过期']);
            $this->userId = (int)$userId;
        }

        parent::initialize(); // TODO: Change the autogenerated stub
    }
}
