<?php
declare (strict_types = 1);

namespace app\index\controller;

use app\BaseController;
use think\App;

class Base extends BaseController
{
    /*
     * 开启批量验证
     */
    protected $batchValidate = true;

    /*
     * 构造函数
     */
    public function __construct(App $app)
    {
        parent::__construct($app);
    }

    /*
     * 初始化函数
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}
