<?php
declare (strict_types = 1);

namespace app\admin\controller;

use app\BaseController;
use app\common\exception\BadRequest as BadRequestException;
use app\common\model\Admin as AdminModel;
use app\common\service\Jwt as JwtService;
use think\App;

class Base extends BaseController
{
    /*
     * 开启批量验证
     */
    protected $batchValidate = true;

    /*
     * 管理员主键
     */
    protected $adminId = 0;

    /*
     * 构造函数
     */
    public function __construct(App $app)
    {
        parent::__construct($app);
    }

    /*
     * 初始化函数
     */
    protected function initialize()
    {
        $jwt = JwtService::getInstance();
        if($jwt->getTableName() === 'admin'){
            //验证token中的id有效性，可增加即时性
            $id = $jwt->getTableId();
            $admin = AdminModel::findOrEmpty($id);
            if($admin->isEmpty()) throw new BadRequestException(['errorMessage' => '管理员不存在或已删除']);
            if($admin->is_use == 2) throw new BadRequestException(['errorMessage' => '账号未启用']);
            $this->adminId = $admin->id;
        }

        parent::initialize(); // TODO: Change the autogenerated stub
    }
}
