<?php
declare (strict_types = 1);

namespace app\admin\controller;

use app\BaseController;
use app\common\exception\BadRequest as BadRequestException;
use app\common\model\Admin as AdminModel;
use app\common\service\Jwt as JwtService;
use app\common\service\Redis as RedisService;
use think\App;

class Base extends BaseController
{
    /*
     * 开启批量验证
     */
    protected $batchValidate = true;

    /*
     * 管理员主键
     */
    protected $adminId = 0;

    /*
     * 构造函数
     */
    public function __construct(App $app)
    {
        parent::__construct($app);
    }

    /*
     * 初始化函数
     */
    protected function initialize()
    {
        $jwt = JwtService::getInstance();
        if($jwt->getTableName() === 'admin'){
            $redis = RedisService::getInstance();
            $adminId = $redis->get('ADMIN:ID:' . $jwt->getTableId());
            if(!$adminId) throw new BadRequestException(['errorMessage' => '管理员ID缓存不存在或已过期']);
            $this->adminId = (int)$adminId;
        }

        parent::initialize(); // TODO: Change the autogenerated stub
    }
}
