<?php
declare (strict_types = 1);

namespace app\admin\controller;

use app\common\exception\BadRequest as BadRequestException;
use app\common\service\Jwt as JwtService;
use app\BaseController;
use think\App;

class Base extends BaseController
{
    /*
     * 开启批量验证
     */
    protected $batchValidate = true;

    /*
     * 管理员主键
     */
    protected $adminId;

    /*
     * 构造函数
     */
    public function __construct(App $app)
    {
        parent::__construct($app);
    }

    /*
     * 初始化函数
     */
    protected function initialize()
    {
        $jwt = JwtService::getInstance();
        if($jwt->getTableName() === app('http')->getName()){
            $this->adminId = $jwt->getTableId();
        }

        parent::initialize(); // TODO: Change the autogenerated stub
    }
}
